In [1]:
import pandas as pd

In [2]:
movies=pd.read_csv(r"E:\movies recommendation dataset\archive (3)\movies.csv")
ratings=pd.read_csv(r"E:\movies recommendation dataset\archive (3)\ratings.csv")

In [3]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [5]:
movies.shape

(9742, 3)

In [6]:
ratings.shape

(100836, 4)

In [7]:
movies.isnull().sum()

movieId    0
title      0
genres     0
dtype: int64

In [8]:
ratings.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [9]:
data=pd.merge(ratings,movies,on="movieId")

In [10]:
data.head()

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [11]:
data['userId'].nunique()

610

In [12]:
data['movieId'].nunique()

9724

In [13]:
user_item_matrix=data.pivot_table(index='userId',columns='title',values='rating')

In [14]:
user_item_matrix

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.5,3.5,NaN,NaN,NaN
609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN,...,NaN,4.0,3.5,3.0,NaN,NaN,2.0,1.5,NaN,NaN

In [15]:
user_item_matrix_filled=user_item_matrix.fillna(0)

In [16]:
user_item_matrix_filled

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.5,3.5,0.0,0.0,0.0
609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
610,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0,...,0.0,4.0,3.5,3.0,0.0,0.0,2.0,1.5,0.0,0.0

In [17]:
user_item_matrix.shape

(610, 9719)

In [18]:
movie_matrix=user_item_matrix_filled.T

In [19]:
from sklearn.metrics.pairwise import cosine_similarity

In [20]:
similarity=cosine_similarity(movie_matrix)

In [21]:
similarity_df=pd.DataFrame(similarity,index=movie_matrix.index,columns=movie_matrix.index)

In [23]:
similarity_df

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.141653,0.000000,...,0.000000,0.342055,0.543305,0.707107,0.0,0.000000,0.139431,0.327327,0.000000,0.0
'Hellboy': The Seeds of Creation (2004),0.000000,1.000000,0.707107,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0
'Round Midnight (1986),0.000000,0.707107,1.000000,0.000000,0.000000,0.0,0.176777,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0
'Salem's Lot (2004),0.000000,0.000000,0.000000,1.000000,0.857493,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0
'Til There Was You (1997),0.000000,0.000000,0.000000,0.857493,1.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
eXistenZ (1999),0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.211467,0.216295,0.097935,0.132489,...,0.000000,0.000000,0.000000,0.000000,0.0,1.000000,0.192259,0.000000,0.170341,0.0
xXx (2002),0.139431,0.000000,0.000000,0.000000,0.000000,0.0,0.089634,0.000000,0.276512,0.019862,...,0.069716,0.305535,0.173151,0.246482,0.0,0.192259,1.000000,0.270034,0.100396,0.0
xXx: State of the Union (2005),0.327327,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.156764,0.000000,...,0.000000,0.382543,0.177838,0.231455,0.0,0.000000,0.270034,1.000000,0.000000,0.0
¡Three Amigos! (1986),0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.372876,0.180009,0.169385,0.249586,...,0.180009,0.000000,0.000000,0.000000,0.0,0.170341,0.100396,0.000000,1.000000,0.0
À nous la liberté (Freedom for Us) (1931),0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.0

In [24]:
def recommend_systems(movie_name,n=5):
    similar_movies=similarity_df[movie_name].sort_values(ascending=False)
    return similar_movies.iloc[1:n+1]

In [26]:
recommend_systems('Toy Story (1995)')

title
Toy Story 2 (1999)                           0.572601
Jurassic Park (1993)                         0.565637
Independence Day (a.k.a. ID4) (1996)         0.564262
Star Wars: Episode IV - A New Hope (1977)    0.557388
Forrest Gump (1994)                          0.547096
Name: Toy Story (1995), dtype: float64

In [27]:
from scipy.sparse.linalg import svds

In [29]:
matrix=user_item_matrix_filled.values

In [30]:
u,sigma,vt=svds(matrix,k=50)

In [32]:
import numpy as np

In [33]:
sigma=np.diag(sigma)

In [34]:
predicted_ratings=np.dot(np.dot(u,sigma),vt)

In [35]:
pred_df=pd.DataFrame(predicted_ratings,columns=user_item_matrix_filled.columns,index=user_item_matrix_filled.index)

In [36]:
pred_df

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,-0.069287,0.018767,-0.042895,-0.038633,-0.049699,-0.007370,0.540617,-0.009627,-0.605885,0.211192,...,0.013099,-0.460020,0.019474,-0.054220,-0.021501,0.339775,-0.286041,-0.187782,1.500375,0.033463
2,-0.028678,-0.012015,-0.010785,0.000667,-0.003074,-0.007729,0.003357,0.008565,0.149107,-0.006173,...,0.004154,-0.015531,-0.027589,-0.034685,0.016193,0.059240,-0.104825,-0.010205,0.056609,-0.000368
3,0.017487,0.001239,0.004907,0.002812,0.002341,-0.001500,0.089847,-0.006716,0.027147,-0.007325,...,0.000466,0.043423,0.022705,0.022107,-0.001260,0.022077,0.001688,0.008866,0.052732,0.003761
4,-0.009402,0.007128,-0.014513,-0.004971,0.017351,-0.033052,-0.372746,0.009112,-0.227757,0.053492,...,-0.004254,-0.145385,-0.069962,-0.057734,0.001657,0.096298,-0.198194,-0.040464,0.015941,-0.005385
5,0.014022,0.004154,0.001643,-0.007565,-0.010141,-0.009996,-0.108389,0.002099,0.011011,-0.096820,...,0.004482,0.048453,0.013028,0.004971,-0.003763,-0.080241,-0.007740,0.045689,-0.091615,0.001638
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.023647,-0.006764,-0.017570,0.027698,0.080438,-0.002075,-0.085235,0.003498,-0.550056,0.091252,...,0.008334,0.060057,0.032516,0.038254,-0.030779,0.068280,0.193172,-0.014553,0.230288,0.009736
607,0.009502,0.015175,0.004493,0.001107,-0.008372,-0.004232,0.244043,0.012814,0.088166,0.174952,...,-0.007348,0.468143,0.056999,0.015934,0.003529,0.429961,0.169634,0.065256,0.179508,0.030917
608,0.001271,-0.081955,-0.056991,-0.005626,-0.032920,-0.043332,0.436091,-0.043894,-0.133154,0.031513,...,0.018198,0.354038,0.016481,0.009475,-0.010645,2.970628,2.386631,0.023173,0.537806,0.017467
609,-0.002226,0.005341,0.005613,-0.001116,-0.009124,0.003415,0.026079,-0.001325,-0.071840,0.011696,...,0.001056,0.019660,0.010333,-0.004505,0.000872,0.008787,-0.005232,0.024702,0.023109,-0.003797
610,3.879142,-0.024543,-0.025389,0.014882,0.032814,-0.016667,0.119515,-0.006774,3.760518,-0.002187,...,0.006174,3.965914,3.398768,2.911950,-0.023952,-0.053707,1.952171,1.422885,-0.258588,0.009695

In [37]:
def get_watched_movies(user_id):
    user_data=user_item_matrix.loc[user_id]
    watched=user_data[user_data>0].index.tolist()
    return watched

In [38]:
def recommend_movies_svd(user_id,n=10):
    user_predictions=pred_df.loc[user_id]
    watched_movies=get_watched_movies(user_id)
    recommendations=user_predictions.drop(watched_movies)
    recommendations=recommendations.sort_values(ascending=False)
    return recommendations.head(n)

In [39]:
recommend_movies_svd(1)

title
Die Hard (1988)                   4.008569
Godfather: Part II, The (1974)    3.304911
Jaws (1975)                       3.302400
Breakfast Club, The (1985)        2.869948
Godfather, The (1972)             2.862019
Stand by Me (1986)                2.785480
Christmas Story, A (1983)         2.602159
Lady and the Tramp (1955)         2.457290
Snatch (2000)                     2.401382
Little Mermaid, The (1989)        2.371714
Name: 1, dtype: float64